const byId = (id) => document.getElementById(id);

export const elements = {
  appContainer: byId("app-container"),
  dynamicBackgroundLayer: byId("dynamic-background-layer"),
  controlsMenu: byId("controls-menu"),
  sketchFolderInputDisplay: byId("sketchFolderInputDisplay"),
  displayTimeInputWrapper: byId("displayTimeInputWrapper"),
  displayTimeInput: byId("displayTime"),
  displayTimeDropdown: byId("displayTimeDropdown"),
  imageCountInput: byId("imageCount"),
  startButton: byId("startButton"),
  mirrorToggle: byId("mirrorToggle"),
  grayscaleToggle: byId("grayscaleToggle"),
  gridToggle: byId("gridToggle"),
  mainMenuHintText: byId("mainMenuHintText"),
  imageCountInputWrapper: byId("imageCountInputWrapper"),
  imageCountDropdown: byId("imageCountDropdown"),
  imageDisplayArea: byId("image-display-area"),
  currentImage: byId("current-image"),
  countdownElement: byId("countdown"),
  countdownProgressTrack: byId("countdown-progress-track"),
  countdownProgressFill: byId("countdown-progress-fill"),
  gridCanvas: byId("grid-canvas"),
  rightControlsHoverZone: byId("right-controls-hover-zone"),
  overlayControls: byId("overlay-controls"),
  openInFinderButton: byId("openInFinderButton"),
  markStarButton: byId("markStarButton"),
  overlayMirrorToggle: byId("overlayMirrorToggle"),
  overlayGrayscaleToggle: byId("overlayGrayscaleToggle"),
  overlayGridToggle: byId("overlayGridToggle"),
  toggleAlwaysOnTopButton: byId("toggleAlwaysOnTopButton"),
  backToMenuButton: byId("backToMenuButton"),
  bottomControlsHoverZone: byId("bottom-controls-hover-zone"),
  imageNavigationControls: byId("image-navigation-controls"),
  prevImageButton: byId("prevImageButton"),
  nextImageButton: byId("nextImageButton"),
  pausePlayButton: byId("pausePlayButton"),
  settingsButton: byId("settings-button"),
  randomPlaybackToggle: byId("random-playback-toggle"),
  filterMarkedToggle: byId("filter-marked-toggle"),
  mainMenuAlwaysOnTopToggle: byId("mainMenuAlwaysOnTopToggle"),
  topRightMenuButtons: byId("top-right-menu-buttons"),
  settingsModalOverlay: byId("settings-modal-overlay"),
  closeSettingsModalButton: byId("closeSettingsModal"),
  mainMenuStaticImagePathRow: byId("mainMenuStaticImagePathRow"),
  mainMenuBackgroundPathDisplay: byId("mainMenuBackgroundPathDisplay"),
  selectMainMenuImageButton: byId("selectMainMenuImageButton"),
  clearMainMenuImageButton: byId("clearMainMenuImageButton"),
  staticImagePathRow: byId("staticImagePathRow"),
  previewBackgroundPathDisplay: byId("previewBackgroundPathDisplay"),
  selectStaticImageButton: byId("selectStaticImageButton"),
  clearStaticImageButton: byId("clearStaticImageButton"),
  gridColorPicker: byId("gridColorPicker"),
  resetGridSettingsButton: byId("resetGridSettingsButton"),
  gridSizeInput: byId("gridSizeInput"),
  settingsModalThemeToggle: byId("settings-modal-theme-toggle"),
  defaultImageFolderPathDisplay: byId("defaultImageFolderPathDisplay"),
  setDefaultImageFolderButton: byId("setDefaultImageFolderButton"),
  clearDefaultImageFolderButton: byId("clearDefaultImageFolderButton"),
  folderBrowserView: byId("folder-browser-view"),
  currentLibraryPathDisplay: byId("current-library-path"),
  thumbnailsGridContainer: byId("thumbnails-grid-container"),
  selectFolderForSketchAndReturnToMenuButton: byId("selectFolderForSketchAndReturnToMenuButton"),
  selectNewFolderFromBrowserButton: byId("selectNewFolderFromBrowserButton"),
  folderBrowserInfoMessage: byId("folderBrowserInfoMessage"),
  goUpFolderButton: byId("goUpFolderButton"),
  libraryFilterMarkedToggle: byId("libraryFilterMarkedToggle"),
  closeFolderBrowserButton: byId("closeFolderBrowserButton"),
  prevPageButton: byId("prevPageButton"),
  nextPageButton: byId("nextPageButton"),
  pageInfoDisplay: byId("pageInfoDisplay"),
  hiddenImageCanvas: byId("hidden-image-canvas"),
  languageSelector: byId("languageSelector"),
};

export const groups = {
  mainMenuBackgroundChoiceRadios: document.querySelectorAll('input[name="mainMenuBackgroundChoice"]'),
  previewBackgroundChoiceRadios: document.querySelectorAll('input[name="previewBackgroundChoice"]'),
  countdownVisibilityRadios: document.querySelectorAll('input[name="countdownVisibility"]'),
  countdownDisplayStyleRadios: document.querySelectorAll('input[name="countdownDisplayStyle"]'),
  startupModeChoiceRadios: document.querySelectorAll('input[name="startupMode"]'),
  displayTimeDropdownOptions: document.querySelectorAll("#displayTimeDropdown .custom-dropdown-option"),
  imageCountDropdownOptions: document.querySelectorAll("#imageCountDropdown .custom-dropdown-option"),
};
